apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: beni2/week-11-test:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8501
